- name: Install fail2ban
  ansible.builtin.apt:
          name: fail2ban
          state: latest
          install_recommends: no

- name: Start fail2ban
  ansible.builtin.systemd_service:
          name: fail2ban
          state: started
          enabled: yes
          daemon_reload: yes

- name: Configure fail2ban
  ansible.builtin.template:
          src: ./fail2ban.conf.j2
          dest: /etc/fail2ban/jail.local
          lstrip_blocks: true
- name: Restart fail2ban
  service:
    name: 'fail2ban'
    state: 'restarted'
