---
- name: Docker installation
  block:
    - name: Installing additional packages
      apt:
        name:
          - ca-certificates 
          - curl gnupg
        update-cache: yes
        update_cache_retries: 86400

    - name: Adding a Docker Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker.gpg
    - name: Install universe
      when: ansible_distribution == 'Ubuntu'
      apt_repository:
        repo: >
          deb [arch=amd64  signed-by=/usr/share/keyrings/docker.gpg]
          https://download.docker.com/linux/{{ ansible_distribution }}
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: yes
        filename: docker

    - name: Docker installation
      apt:
        name: 
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        update-cache: yes

    - name: Checking Docker is Installed and Reloaded
      service:
        name: docker
        state: restarted
        enabled: yes
  become: true
- name: Completing the installation
  block:
    - name: Create a docker group
      group:
        name: docker
        state: present

    - name: Adding a user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
  become: true
